### ISSUE TITLE
running `rake db:seed` throwing an error

### ISSUE THREAD

**Issue by nijeesh4all** [coronasafe/coronaRM#8]
Running `rake db:seed` throws this error.
```
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/user/coronaRM/data/traveller_2.csv
/Users/user/coronaRM/db/seeds.rb:46:in `populate_traveller_from_data_file'
/Users/user/coronaRM/db/seeds.rb:72:in `<main>'
```

I think there should be a condition for checking if the file exists in the `populate_patients_from_data_file` and `populate_traveller_from_data_file` method. 

or better these should be moved  to a rake task if it is not used for bootstrapping the database.

**Comment by aswinmohanme** [comment]
The data is highly confidential, that's why the file is not there. Also we can skip this check since we are the only ones who would be running this right ?

**Comment by nijeesh4all** [comment]
If that data is not necessary we can move the function to import the CSV to a rake task. 
Since that's not what seed is for. 

since its not a high priority we can merge this issue with the code improvements. #7 

what are your thoughts ?
